<Project Sdk="Microsoft.NET.Sdk.Web">
	<PropertyGroup>
	  <UserSecretsId>13dfbeca-5d6d-4ccc-96ec-4714b1bc1a0e</UserSecretsId>
	  <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
	  <DockerComposeProjectPath>..\docker-compose.dcproj</DockerComposeProjectPath>
	</PropertyGroup>
	<ItemGroup>
		<PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" />
		<PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" />
		<PackageReference Include="Microsoft.Build" />
		<PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" />
		<PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" />
		<PackageReference Include="Refit.HttpClientFactory" />
	</ItemGroup>
	<ItemGroup>
		<ProjectReference Include="..\DynamicPrice.Client.Infrastructure\DynamicPrice.Client.Infrastructure.csproj" />
		<ProjectReference Include="..\DynamicPrice.Shared.Contracts\DynamicPrice.Shared.Contracts.csproj" />
	</ItemGroup>
</Project>
