<Project Sdk="Microsoft.NET.Sdk.Razor">
	<ItemGroup>
		<SupportedPlatform Include="browser" />
	</ItemGroup>
	<ItemGroup>
		<FrameworkReference Include="Microsoft.AspNetCore.App" />
	</ItemGroup>
	<ItemGroup>
		<PackageReference Include="Microsoft.Build" />
		<PackageReference Include="Refit" />
		<PackageReference Include="System.IdentityModel.Tokens.Jwt" />
	</ItemGroup>
	<ItemGroup>
	  <ProjectReference Include="..\DynamicPrice.Shared.Contracts\DynamicPrice.Shared.Contracts.csproj" />
	</ItemGroup>
</Project>
